#!/usr/bin/env python3
"""Recover inherited merge artifacts without erasing transactional state.

The hourly publisher may inherit a conflict committed by an earlier racing
writer.  Recovery is deliberately conservative:

* predictions_log.csv is parsed as CSV and unioned by its composite key;
* JSON state/artifacts are restored from the validated ``origin/main`` blob;
* alert_state.json is never reset -- if recovery is impossible, publishing
  fails closed after quarantining the corrupt bytes under the system temp dir;
* docs artifacts are restored, not deleted, because historical pages are not
  necessarily regenerated by the current run.

The publish gate still runs after generation and after every rebase.
"""
import csv
import io
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PREDICTION_FIELDS = [
    "prediction_made_at", "target_tide_time", "hours_until_peak",
    "predicted_mllw_astronomical", "surge_ft_predicted", "surge_source",
    "sh_peak_mllw_predicted", "peak_rain_in_hr_predicted",
    "water_navd88_predicted", "regime_predicted", "cold_lockout",
    "confidence_level", "model_version",
]


def _has_markers(blob):
    return b"<<<<<<< " in blob or b">>>>>>> " in blob


def _origin_blob(relpath, root=ROOT):
    """Read one exact file from origin/main; never mutate git state."""
    proc = subprocess.run(
        ["git", "show", f"origin/main:{relpath}"],
        cwd=root, capture_output=True, check=False,
    )
    if proc.returncode:
        why = proc.stderr.decode("utf-8", "replace").strip()
        raise RuntimeError(f"cannot recover {relpath} from origin/main: {why}")
    return proc.stdout


def _quarantine(path):
    """Move damaged bytes out of the repository and return their new path."""
    qdir = Path(tempfile.mkdtemp(prefix="barnacle-recovery-"))
    target = qdir / path.name
    os.replace(path, target)
    return target


def _atomic_write(path, blob):
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_bytes(blob)
    os.replace(tmp, path)


def _restore_from_origin(path, root=ROOT, require_json=False):
    relpath = path.relative_to(root).as_posix()
    replacement = _origin_blob(relpath, root)
    if _has_markers(replacement):
        raise RuntimeError(f"origin/main copy of {relpath} also has markers")
    if require_json:
        parsed = json.loads(replacement.decode("utf-8"))
        if not isinstance(parsed, dict):
            raise RuntimeError(f"origin/main copy of {relpath} is not an object")
    quarantined = _quarantine(path)
    _atomic_write(path, replacement)
    return quarantined


def _repair_predictions(path):
    """Strictly parse marker-stripped CSV and union by prediction key."""
    lines = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith(("<<<<<<<", "=======", ">>>>>>>")):
            continue
        if line.strip():
            lines.append(line)
    reader = csv.reader(io.StringIO("\n".join(lines)), strict=True)
    parsed = list(reader)
    if not parsed or parsed[0] != PREDICTION_FIELDS:
        raise RuntimeError("predictions_log.csv header is missing or invalid")
    by_key = {}
    for logical_row, row in enumerate(parsed[1:], 2):
        if row == PREDICTION_FIELDS:  # duplicate branch header
            continue
        if len(row) != len(PREDICTION_FIELDS):
            raise RuntimeError(
                f"predictions_log.csv row {logical_row} has {len(row)} fields"
            )
        key = (row[0], row[1])
        prior = by_key.get(key)
        if prior is not None and prior != row:
            raise RuntimeError(
                "conflicting prediction rows share key " + repr(key)
            )
        by_key[key] = row
    rows = [by_key[key] for key in sorted(by_key)]
    out = io.StringIO(newline="")
    writer = csv.writer(out, lineterminator="\n")
    writer.writerow(PREDICTION_FIELDS)
    writer.writerows(rows)
    _atomic_write(path, out.getvalue().encode("utf-8"))
    return len(rows)


def heal_tree(root=ROOT):
    root = Path(root)
    healed = []

    log = root / "data" / "predictions_log.csv"
    if log.exists() and _has_markers(log.read_bytes()):
        count = _repair_predictions(log)
        healed.append(f"predictions_log.csv CSV-unioned ({count} rows)")

    for name in ("alert_state.json", "tide_predictions_cache.json"):
        path = root / "data" / name
        if not path.exists():
            continue
        blob = path.read_bytes()
        bad = _has_markers(blob)
        if not bad:
            try:
                json.loads(blob.decode("utf-8"))
            except Exception:
                bad = True
        if bad:
            quarantined = _restore_from_origin(path, root, require_json=True)
            healed.append(
                f"{name} restored from origin/main "
                f"(corrupt copy quarantined at {quarantined})"
            )

    docs = root / "docs"
    if docs.exists():
        for path in docs.rglob("*"):
            if not path.is_file():
                continue
            try:
                marked = _has_markers(path.read_bytes())
            except OSError:
                continue
            if marked:
                quarantined = _restore_from_origin(
                    path, root, require_json=path.suffix == ".json"
                )
                healed.append(
                    f"docs: restored {path.relative_to(root)} from origin/main "
                    f"(corrupt copy quarantined at {quarantined})"
                )
    return healed


def main():
    try:
        healed = heal_tree()
    except Exception as exc:
        print(f"RECOVERY FAILED CLOSED: {exc}", file=sys.stderr)
        return 1
    if healed:
        print("HEALED:")
        for item in healed:
            print("  -", item)
    else:
        print("tree healthy — nothing to heal")
    return 0


if __name__ == "__main__":
    sys.exit(main())
